name: Scheduled Model Training

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      ZENML_STACK_NAME: ${{ secrets.ZENML_STACK_NAME }}
      ZENML_PROJECT_NAME: ${{ secrets.ZENML_PROJECT_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and initialize ZenML
        run: |
          pip install -r requirements.txt
          git init  # ZenML needs this
          zenml init

      - name: Import ZenML stack
        run: |
          zenml stack delete bankruptcy_risk_stack || true
          zenml stack import bankruptcy_risk_stack.yaml

      - name: Set ZenML project and stack
        run: |
          zenml project set "$ZENML_PROJECT_NAME"
          zenml stack set "$ZENML_STACK_NAME"

      - name: Run ZenML pipeline
        run: python run_deploy_pipeline.py
