name: Scheduled Model Training

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_DEFAULT_REGION: 'us-ease-1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Pull DVC data/artifacts
        run: |
          dvc pull --verbose

      - name: Initialize ZenML repo and import stack
        run: |
          zenml init
          zenml stack delete bankruptcy_risk_stack || true
          zenml stack import bankruptcy_risk_stack.yaml

      - name: Set ZenML project and stack
        run: |
          zenml stack set bankruptcy_risk_stack

      - name: Show repo file structure
        run: |
          echo "📁 Showing current working directory:"
          pwd
          echo "📂 Listing all files and folders:"
          ls -R

      - name: Run ZenML pipeline
        run: python run_deploy_pipeline.py
